"""SQLAlchemy 2.0 declarative models for the state store.

WP2 / T2.2. Four tables, all dialect-portable (SQLite today, PostgreSQL later via the
same schema and the same Alembic migration): ``identity_map``, ``watermarks``,
``field_envelopes`` and ``orphan_log``. Column names and grouping follow the SDK
neutral model (:mod:`qlabs_catalog_sync_sdk.models`) rather than inventing a parallel
vocabulary:

* ``identity_map`` persists :class:`~qlabs_catalog_sync_sdk.models.IdentityRef`
  (``endpoint``, ``entity_type``, ``native_key``, ``tenant_id``, ``secondary_keys``)
  bound to an engine-assigned ``neutral_id``, plus the explicit bootstrap-match
  confirmation flag T7.1 exposes (RS-03 section 4: "require human confirmation
  before binding").
* ``field_envelopes`` persists one
  :class:`~qlabs_catalog_sync_sdk.models.FieldEnvelope` per (entity, field, endpoint)
  — the same five provenance columns the SDK envelope carries, plus ``value_json``.
* ``watermarks`` persists one opaque resume token per (sync pair, endpoint, entity
  type) — never a typed column, since the token shape is source-defined (a
  timestamp, an RFC3339 string, or a page cursor).
* ``orphan_log`` is the D4 record of a source object that vanished: v1 never deletes
  in Qlik, so a disappearance is recorded here (first/last seen missing) and
  surfaced in the run report instead.

No table here holds credential material — the state store persists identity,
watermark and provenance metadata only.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import JSON, Boolean, MetaData, String, Text, UniqueConstraint, Uuid
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from qlabs_catalog_sync.state.types import UTCDateTime

__all__ = [
    "Base",
    "FieldEnvelopeRow",
    "IdentityMapRow",
    "OrphanLogRow",
    "WatermarkRow",
]

# A named-constraint convention so autogenerated DDL (and any future Alembic
# autogenerate diff) produces stable, predictable constraint names on every
# dialect instead of dialect-assigned anonymous names.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by every state-store table."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class IdentityMapRow(Base):
    """Neutral id <-> native key, one row per (neutral_id, endpoint, entity_type).

    Mirrors :class:`~qlabs_catalog_sync_sdk.models.IdentityRef`. Native keys are only
    unique within a tenant (RS-03 section 4), so ``tenant_id`` is part of the
    uniqueness constraint used both for the reverse (native-key -> neutral_id) lookup
    bootstrap matching needs and for rejecting a second binding of the same native
    key at the same endpoint+tenant. ``confirmed`` models the explicit human
    confirmation step bootstrap matching requires before a natural-key match becomes
    a trusted binding (T7.1); it defaults to unconfirmed.
    """

    __tablename__ = "identity_map"
    __table_args__ = (
        UniqueConstraint(
            "endpoint",
            "entity_type",
            "tenant_id",
            "native_key",
            name="uq_identity_map_endpoint_entity_type_tenant_id_native_key",
        ),
    )

    # Composite PK: one row per neutral entity per endpoint it is known at. A given
    # neutral_id is intrinsically one entity_type, but entity_type is kept in the key
    # (matching the SDK's IdentityRef shape) so lookups never need a join elsewhere
    # to discover the type.
    neutral_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True)
    endpoint: Mapped[str] = mapped_column(String(128), primary_key=True)
    entity_type: Mapped[str] = mapped_column(String(64), primary_key=True)

    tenant_id: Mapped[str] = mapped_column(String(255), nullable=False)
    native_key: Mapped[str] = mapped_column(Text, nullable=False)
    # dict[str, str], e.g. Qlik's `id`/`resourceId` alongside the primary secureQri.
    secondary_keys: Mapped[dict[str, Any]] = mapped_column(JSON, nullable=False, default=dict)

    confirmed: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    confirmed_at: Mapped[datetime | None] = mapped_column(UTCDateTime())

    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(UTCDateTime(), nullable=False)


class WatermarkRow(Base):
    """Per (sync pair, endpoint, entity type) poll position.

    ``watermark_token`` is stored as opaque text -- a timestamp, an RFC3339 string,
    or a page cursor depending on the source -- never a typed column that assumes
    one shape, per the source adapter's ``list_changed`` contract (RS-07 section 2).
    """

    __tablename__ = "watermarks"

    sync_pair: Mapped[str] = mapped_column(String(128), primary_key=True)
    endpoint: Mapped[str] = mapped_column(String(128), primary_key=True)
    entity_type: Mapped[str] = mapped_column(String(64), primary_key=True)

    watermark_token: Mapped[str | None] = mapped_column(Text)
    last_run_at: Mapped[datetime | None] = mapped_column(UTCDateTime())
    last_status: Mapped[str | None] = mapped_column(String(32))

    updated_at: Mapped[datetime] = mapped_column(UTCDateTime(), nullable=False)


class FieldEnvelopeRow(Base):
    """Last-known field envelope per (entity, field, endpoint).

    Mirrors :class:`~qlabs_catalog_sync_sdk.models.FieldEnvelope`. The diff baseline
    and the idempotency ledger: a sync cycle only writes when a
    freshly computed checksum differs from ``checksum`` here. The composite primary
    key is ordered ``(neutral_id, endpoint, entity_type, field)`` so "every envelope
    for one entity at one endpoint" is a single indexed prefix scan, not a table
    scan. ``value_json`` holds the envelope's arbitrary JSON value (strings, tag
    arrays, nested objects) losslessly via the portable ``JSON`` type.
    """

    __tablename__ = "field_envelopes"

    neutral_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True)
    endpoint: Mapped[str] = mapped_column(String(128), primary_key=True)
    entity_type: Mapped[str] = mapped_column(String(64), primary_key=True)
    field: Mapped[str] = mapped_column(String(128), primary_key=True)

    value_json: Mapped[Any] = mapped_column(JSON, nullable=True)
    source_endpoint: Mapped[str | None] = mapped_column(String(128))
    source_revision: Mapped[str | None] = mapped_column(Text)
    last_modified_at: Mapped[datetime | None] = mapped_column(UTCDateTime())
    last_synced_at: Mapped[datetime | None] = mapped_column(UTCDateTime())
    checksum: Mapped[str | None] = mapped_column(String(128))

    updated_at: Mapped[datetime] = mapped_column(UTCDateTime(), nullable=False)


class OrphanLogRow(Base):
    """D4 orphan record: a source object that vanished, never deleted in Qlik.

    One row per (neutral_id, endpoint, entity_type) that has ever been seen missing
    from ``endpoint``. ``first_missing_at``/``last_missing_at`` record when it was
    first and most recently observed absent; ``resolved_at`` is set if the object
    reappears (and cleared again if it later vanishes a second time), so the run
    report can distinguish a currently-missing orphan from a historical one.
    """

    __tablename__ = "orphan_log"

    neutral_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True)
    endpoint: Mapped[str] = mapped_column(String(128), primary_key=True)
    entity_type: Mapped[str] = mapped_column(String(64), primary_key=True)

    native_key: Mapped[str | None] = mapped_column(Text)
    first_missing_at: Mapped[datetime] = mapped_column(UTCDateTime(), nullable=False)
    last_missing_at: Mapped[datetime] = mapped_column(UTCDateTime(), nullable=False)
    last_seen_at: Mapped[datetime | None] = mapped_column(UTCDateTime())
    resolved_at: Mapped[datetime | None] = mapped_column(UTCDateTime())
